version: '2'

services: 
    web:
        build: .
        image: simple_trello_web
        volumes: 
            - ./:/src
            - /src/node_modules
        ports: 
            - '5001:5000'
#        depends_on: 
#            - mongo
    
#    mongo:
#        image: mongo
#        ports: 
#            - '27017:27017'
#        volumes: 
#            - /data/db
